"""next

Revision ID: 304d0daec970
Revises: c31ae60741f2
Create Date: 2022-12-20 01:40:00.404803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304d0daec970'
down_revision = 'c31ae60741f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mf', sa.Column('actived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mf', 'actived')
    # ### end Alembic commands ###
