"""next

Revision ID: c31ae60741f2
Revises: 
Create Date: 2022-12-20 01:25:38.019852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31ae60741f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie_capteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpio_bcm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sonde',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.Column('en_service', sa.Boolean(), nullable=True),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.Column('chemin', sa.String(length=200), nullable=True),
    sa.Column('type_sonde', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appareil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('categorieappareil', sa.String(length=200), nullable=True),
    sa.Column('sortie', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('order_gpio', sa.String(length=200), nullable=True),
    sa.Column('nbre_gpio', sa.Integer(), nullable=True),
    sa.Column('sonde_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=250), nullable=True),
    sa.Column('sonde_actived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sonde_id'], ['sonde.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valeur_sonde',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=True),
    sa.Column('sonde_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sonde_id'], ['sonde.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appareil_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['appareil_id'], ['appareil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('valeur', sa.String(length=10), nullable=True),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.Column('appareil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appareil_id'], ['appareil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manuel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appareil_id', sa.Integer(), nullable=True),
    sa.Column('ordre', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['appareil_id'], ['appareil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debut', sa.DateTime(), nullable=True),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('appareil_mf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appareil_mf'], ['appareil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mode_de_marche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appareil_id', sa.Integer(), nullable=False),
    sa.Column('mode_de_marche', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['appareil_id'], ['appareil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programmation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('start_min', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('end_min', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('appareil', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appareil'], ['appareil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programmation')
    op.drop_table('mode_de_marche')
    op.drop_table('mf')
    op.drop_table('manuel')
    op.drop_table('gpio')
    op.drop_table('auto')
    op.drop_table('valeur_sonde')
    op.drop_table('appareil')
    op.drop_table('user')
    op.drop_table('status')
    op.drop_table('sonde')
    op.drop_table('gpio_bcm')
    op.drop_table('categorie_capteur')
    # ### end Alembic commands ###
