"""empty message

Revision ID: c4156fdaf9af
Revises: 304d0daec970
Create Date: 2022-12-22 15:09:27.212748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4156fdaf9af'
down_revision = '304d0daec970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appareil', sa.Column('min', sa.Float(), nullable=True))
    op.add_column('appareil', sa.Column('max', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appareil', 'max')
    op.drop_column('appareil', 'min')
    # ### end Alembic commands ###
